# Generated by Django 4.2.2 on 2024-09-14 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=250)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='images/collections/')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('products', models.ManyToManyField(blank=True, related_name='collections', to='store.product')),
            ],
            options={
                'verbose_name_plural': 'collections',
            },
        ),
    ]
