# Generated by Django 4.2.2 on 2024-09-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
