# Generated by Django 4.2.2 on 2024-09-13 20:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 13, 20, 36, 52, 342484, tzinfo=datetime.timezone.utc)),
        ),
    ]
