# Generated by Django 4.2.2 on 2023-06-25 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
        migrations.AddField(
            model_name='order',
            name='ShippingAddress',
            field=models.TextField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
