# Generated by Django 4.2.2 on 2023-06-25 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_remove_order_shipping_address_order_shippingaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ShippingAddress',
            new_name='shipping_address',
        ),
    ]
