# Generated by Django 4.2.2 on 2024-09-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_rename_shippingaddress_order_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Order placed'), ('processing', 'Product packaging'), ('shipped', 'Ready for shipment'), ('trucking', 'On the way'), ('arrived', 'Dropped in the delivery station'), ('delivered', 'Delivered'), ('out of stock', 'Out of stock')], default='pending', max_length=20),
        ),
    ]
